name: Repo Sync

on:
  schedule: 
  - cron: '0 0 * * *'
  repository_dispatch:
    types: [webhook-event]
  
  workflow_dispatch:

jobs:
  repo-sync:
    name: Repo Sync
    runs-on: ubuntu-latest
    steps:
    - name: Checkout public repo code
      uses: actions/checkout@v3
    - name: Set up Git configuration
      run: |
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"

