name: Repo Sync

on:
  schedule: 
  - cron: '0 0 * * *'  # Runs at midnight every day
  workflow_dispatch:

jobs:
  repo-sync:
    name: Repo Sync
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with :
        ref: repo-sync
    - uses: repo-sync/github-sync@v2
      name: Sync internal code repo to main branch 
      with:
        source_repo: ${{ secrets.SOURCE_REPO }}
        source_branch: main
        destination_branch: main
        github_token: ${{ secrets.WORKFLOW_TOKEN }}

